import React from "react";
import Work from "./Work";

const WorkList = () => {
  return (
    <div className="flex flex-col mt-8 md:mt-16 space-y-4 mx-8 md:mx-16 lg:mx-32 lg:px-24">
      <h1 className="text-2xl md:text-4xl lg:text-4xl underline font-bold">
        Work Experiance
      </h1>
      <div className="flex gap-y-4 md:gap-y-8 flex-col">
        <Work
          key={1}
          company="Collaborative Learning Labs(Collabll)"
          date="July, 2021 - Present"
          details={[
            "Contributed to the development of a question-answering system for the legal domain by researching and developing deep learning models.",
            "Improved existing language translation models to work with Indic languages for the legal domain by implementing new algorithms and methods.",
            "Created an efficient way to extract relevant Indian law by developing a new information retrieval system.",
          ]}
          technologies={["Python", "NLP", "Haystack", "Hugging Face"]}
        />
        <Work
          key={2}
          company="Tata Consultancy Services(TCS)"
          date="November, 2021 - May, 2022"
          details={[
            "Worked with a senior machine learning engineer to build a chatbot that used NLP to retrieve information from websites.",
            "The chatbot was able to reduce the time users spend on websites searching for information.",
            "The project was successful and the website users were able to find information faster.",
          ]}
          technologies={[
            "Python",
            "Pytorch",
            "NLP",
            "Haystack",
            "Hugging Face",
          ]}
        />
        <Work
          key={3}
          company="Envelor Corporation"
          date="February, 2020 - December, 2020"
          details={[
            "Developed analysis of the e-commerce data generated by the company to help improve sales.",
            "Collaborated with the sales team to create an ERP system that tracks and manages sales.",
            "Utilised Python, Google Data Studio and PowerBI to develop the analysis.",
          ]}
          technologies={["Python", "PowerBI", "Google Data Studio", "PHP"]}
        />
        <Work
          key={5}
          company="Sanesquare Technologies"
          date="July, 2020 - November, 2020"
          details={[
            "Assisted in building a cross-platform social media platform like TikTok",
            "Handled the authentication and profile section of the application",
          ]}
          technologies={["Javascript", "ReactJS", "React Native"]}
        />
      </div>
    </div>
  );
};

export default WorkList;
